# Generated by Django 3.1.3 on 2022-04-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20220405_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='vote_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
