# Generated by Django 3.1.3 on 2022-04-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_comment_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
