# Generated by Django 3.1.3 on 2022-04-08 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0009_auto_20220406_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='comment',
            name='hater',
            field=models.ManyToManyField(related_name='hater_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
